// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUZfKSCRnH2wAmkrGO12OKihBkmDXF1o',
    appId: '1:139965024838:web:116a9639137e6e79845847',
    messagingSenderId: '139965024838',
    projectId: 'wisataapk',
    authDomain: 'wisataapk.firebaseapp.com',
    storageBucket: 'wisataapk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlYaOg0DiZ9r3mW38Nq1zfRmQxiHTmgI',
    appId: '1:139965024838:android:c6cdd8ecaf958330845847',
    messagingSenderId: '139965024838',
    projectId: 'wisataapk',
    storageBucket: 'wisataapk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRuBXo7wA_GYw9tNPP6X4pzyj41jCY1C8',
    appId: '1:139965024838:ios:49e21f4d2c9cae89845847',
    messagingSenderId: '139965024838',
    projectId: 'wisataapk',
    storageBucket: 'wisataapk.firebasestorage.app',
    iosBundleId: 'com.example.wisatasurabaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRuBXo7wA_GYw9tNPP6X4pzyj41jCY1C8',
    appId: '1:139965024838:ios:49e21f4d2c9cae89845847',
    messagingSenderId: '139965024838',
    projectId: 'wisataapk',
    storageBucket: 'wisataapk.firebasestorage.app',
    iosBundleId: 'com.example.wisatasurabaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqUZfKSCRnH2wAmkrGO12OKihBkmDXF1o',
    appId: '1:139965024838:web:ccfc2d7f3deeae9b845847',
    messagingSenderId: '139965024838',
    projectId: 'wisataapk',
    authDomain: 'wisataapk.firebaseapp.com',
    storageBucket: 'wisataapk.firebasestorage.app',
  );
}
